### ISSUE TITLE
Publish theme to NPM

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge-nr-launcher#134]
### Description

Now that the theme is part of launcher our new Remote Device Editor cannot be themed as FF. 

This FR is to have the theme remain part of this repo but to also be published to NPM as its own package to that it can be `require`d by the device agent.

See [Agent #89](https://github.com/flowforge/flowforge-device-agent/issues/89) for more info.

**Comment by knolleary** [comment]
To be clear - this isn't a feature request - it is a necessary task of https://github.com/flowforge/flowforge-device-agent/issues/89 and should be completed in 1.9.

**Comment by hardillb** [comment]
How do we want to version the theme?

- On it's own version
- In sync with the launcher?

**Comment by Steve-Mcl** [comment]
This will be verified during release process.

- [ ] Verify theme gets updated as part of release process.
