### ISSUE TITLE
Editor environment variables: allow controllable propagation of env set to Editor process with the hosting operators

### ISSUE THREAD

**Issue by elenaviter** [flowforge/flowforge-nr-launcher#144]
### Environment variables, sources
In the environment that the Node-RED process operates, there are 2 sources for the environmental variables it will adopt:

- Variables set on the project settings in FlowForge.
- Variables related to FlowForge project identification. These are needed for Node-RED to communicate with the storage endpoints of FlowForge via the storage plugin.

However, there's third which is needed:
- Variables that come into play when the Editor instance (and by extension, the Device instance, though that's a separate discussion) is deployed via a container orchestrator. These variables can also be introduced in other situations where operators add their environment variables to the instance dynamically (even if this 'orchestrator' is just a docker run on local machine and me who want to set the environment variables for this run).

### Illustration of the need for dynamically provisioned env propagation, to Node-RED
Take for example the scenario where Project instance runs in a Kubernetes environment. By using annotations and labels, you can direct controllers to the appropriate deployment. Kubernetes operators and controllers, in turn, can set custom environments for instances launched under their control. 
A good example of this dynamic provisioning of environmental variables is the linkage of IAM via service account. When a controller of this service account notices a new pod is up and running and linked to a controlled service account, it can mount IAM secrets to the pod and set the environmental variables. Consequently, the software running on the pod is empowered to assume cloud IAM (such as AWS, Azure, etc.) and operate seamlessly, transparently, via linking the web identity by controllers in form of env variables.

Please note that this is only one example of how environmental variables can be **dynamically provisioned**. There are variables and values which cannot be set from the Project Settings.

To forward these environment variables to Node-RED (as well as software solutions running in Node-RED), we need to imbue the launcher with the ability to augment the application's environment with `process.env`. 

Instead of the usual [way that Node-RED process will assume env](https://github.com/flowforge/flowforge-nr-launcher/blob/8b1a2793f82fb43dcf3df2c2429308a832ec1d80/lib/launcher.js#L273) includes:
- env set on Project Settings in FlowForge
- env with FF project identification needed for Node-RED to communicate to storage via storage plugin

E.g. instead
```javascript
const appEnv = Object.assign({}, this.env, this.settings.env)
```

We propose to filter the `process.env` to exclude variables starting with "FORGE", which stands for servicing FORGE secrets:
```javascript
const filter_env = (env) =>
    Object.entries(env).reduce((acc, [key, value]) =>
          key.startsWith('FORGE') ? acc : {...acc, [key]: value}, {});
const appEnv = Object.assign({}, filter_env(process.env), this.env, this.settings.env)
```

Or alternatively, in a more controlled approach, we propose using a documented environment variable, such as `FORGE_ALLOW_MANAGED_ENV_IN_EDITOR`. This variable should be set on the project setting to unlock this propagation. This approach ensures that users are aware of the implications and potential benefits of the propagation.

```javascript
const filter_env = (env) =>
    Object.entries(env).reduce((acc, [key, value]) =>
          key.startsWith('FORGE') ? acc : {...acc, [key]: value}, {});
        
const appEnv = Object.assign({},
    this.settings.env.FORGE_ALLOW_MANAGED_ENV_IN_EDITOR ? filter_env(process.env) : {}, 
    this.env, 
    this.settings.env)
```

**Comment by elenaviter** [comment]
Hello @knolleary,

I trust this message finds you well. I am reaching out to inform you about [related pull request](https://github.com/flowforge/flowforge-nr-launcher/pull/145) where I noticed some conflicts with the main branch. 
To streamline the process, I've gone ahead and resolved these conflicts, making the PR ready for another round of review at your convenience.

Your insights are valuable, and I look forward to any further suggestions you may have.
Thank you once again for your time and effort 🙂

**Comment by ggworld** [comment]
@knolleary - Any news on this,
this is a must to use the licensed FF we purchased

**Comment by knolleary** [comment]
Delivered by #145
