### ISSUE TITLE
Provide `credentialSecret` rather than rely on randomly generated one

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge-nr-launcher#16]
### Description

Right now we let NR generate the `_credentialSecret` and store it in the runtime settings.

This means NR logs the big warning about using the auto-generated secret whenever it starts up.

It would be better to use a secret we generate. This will need some co-ordination with the core which will be responsible for generating and providing the secret at startup.

1. Do we generate a secret and store it in the core Projects model?
2. Or do we use something derived from the project id/hashid and manage that entirely in the launcher?

**Comment by hardillb** [comment]
It needs to be recoverable in the management app to allow for the potential of cloning of projects with credentials

**Comment by sammachin** [comment]
This is related to #270 as when exporting a project the credentialSecret is a component of that

**Comment by knolleary** [comment]
Here is my proposed design - that balances security and convenience.

1. When a Project is created, we generate a credential secret and store it as a `ProjectSetting`: 
    `project.updateSetting('credentialSecret', generatedSecret)`
2. This gets passed to the launcher alongside the other access tokens - *not* via the `/settings` end point - and inserted into the settings file as normal

Aside: this same value can be used to encrypt secure Env Vars as well - One Ring To Rule Them All.

For the export/copy scenario I think it is important that the new copy uses its *own* key. To achieve that the forge app should be able to use the same algorithm as Node-RED to decrypt with the current project's key and then re-encrypt with a new key.

When copying to a new project (or into an existing one) - the forge app will use the destination project's key (the generated in step 1 above).

When exporting outside of the system boundary, it should be necessary for the user to provide a key at the point of export, to use to encrypt the values.

**Comment by knolleary** [comment]
There are two remaining tasks before this can be considered complete:

 - https://github.com/flowforge/flowforge-driver-k8s/issues/37
 - https://github.com/flowforge/flowforge-driver-docker/issues/22

**Comment by ZJvandeWeg** [comment]
@Steve-Mcl @knolleary Can this issue be closed? My understanding from the comments it can.
