### ISSUE TITLE
Remove node-red as an explicit dependency

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge-nr-launcher#47]
### Description

The fact the launcher depends on the `node-red` module comes from before we introduced stacks.

I don't think there is any reason to keep node-red as a dependency of the launcher - but need to double check that assumption. Given how close we are to 0.7, I wouldn't want to destabilise anything unless we're 100% certain there are unintended consequences here.

Would appreciate your opinion on this @hardillb

**Comment by hardillb** [comment]
I think we are safe to remove it, but I would want to run a quick Docker container test to be 100% sure (I can do that before lunch today)
